/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kyPkg.panel;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import static kyPkg.panel.JP_Ancestor.standAlone;

import kyPkg.filter.Flt_Head;
import kyPkg.uFile.FileUtil;
import kyPkg.util.DnDAdapter;

/**
 *
 * @author ejqp7
 */
public class Pn_Head extends javax.swing.JPanel {

    /**
     * Creates new form Pn_CompareEx
     */
    public Pn_Head() {
        super();
        setSize(620, 480);
        this.setOpaque(false);
        initComponents();
        new java.awt.dnd.DropTarget(txtFile1, new DnDAdapter(txtFile1)); // dnd.DropTarget
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtFile1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLimit = new javax.swing.JTextField();
        btnCompare = new javax.swing.JButton();
        btnWriteIt = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLeft = new javax.swing.JTextArea();

        setFont(new java.awt.Font("ＭＳ ゴシック", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMaximumSize(new java.awt.Dimension(940, 60));
        jPanel2.setMinimumSize(new java.awt.Dimension(940, 60));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(940, 60));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        txtFile1.setFont(new java.awt.Font("ＭＳ ゴシック", 0, 12)); // NOI18N
        txtFile1.setMaximumSize(new java.awt.Dimension(600, 25));
        txtFile1.setMinimumSize(new java.awt.Dimension(600, 25));
        txtFile1.setOpaque(true);
        txtFile1.setPreferredSize(new java.awt.Dimension(600, 25));
        jPanel2.add(txtFile1);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 35));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 35));

        jLabel1.setText("表示する行数");
        jPanel1.add(jLabel1);

        txtLimit.setText("100");
        jPanel1.add(txtLimit);

        btnCompare.setFont(new java.awt.Font("ＭＳ ゴシック", 0, 12)); // NOI18N
        btnCompare.setText("実行");
        btnCompare.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompareActionPerformed(evt);
            }
        });
        jPanel1.add(btnCompare);

        btnWriteIt.setFont(new java.awt.Font("ＭＳ ゴシック", 0, 12)); // NOI18N
        btnWriteIt.setText("Write");
        btnWriteIt.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriteItActionPerformed(evt);
            }
        });
        jPanel1.add(btnWriteIt);

        btnReset.setFont(new java.awt.Font("ＭＳ ゴシック", 0, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset);

        jPanel2.add(jPanel1);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        txtLeft.setColumns(20);
        txtLeft.setFont(new java.awt.Font("ＭＳ ゴシック", 0, 12)); // NOI18N
        txtLeft.setRows(5);
        txtLeft.setTabSize(4);
        jScrollPane1.setViewportView(txtLeft);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void btnCompareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompareActionPerformed
            head();
	}//GEN-LAST:event_btnCompareActionPerformed

	private void btnWriteItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteItActionPerformed
            writeIt();
	}//GEN-LAST:event_btnWriteItActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtFile1.setText("");
        txtLeft.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void head() {
        String rStr = "";
        String wPath1 = txtFile1.getText();
        if (wPath1.trim().equals("")) {
            wPath1 = "./left.txt";
            txtFile1.setText(wPath1);
            FileUtil.string2file_(wPath1, txtLeft.getText());
        }
        List<String> statLog = new ArrayList();

        //ファイルの先頭を256行取り出して出力する
        int limit = 256;
        String strLimit = txtLimit.getText();
        try {
            limit = Integer.parseInt(strLimit);
        } catch (Exception e) {
            e.printStackTrace();
        }
        Flt_Head ins = new Flt_Head(wPath1, limit);
        ins.execute();
        //		List<String> result = ins.getResult();
        txtLeft.setText(ins.getResultStr());

    }

    public void test_readIt() {
        String wPath = txtFile1.getText().trim();
        if (wPath.equals("")) {
            JFileChooser fc = new JFileChooser(".");
            if (fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                wPath = fc.getSelectedFile().toString();
            }
        }
        txtLeft.setText(FileUtil.file2String(wPath));
    }

    private void writeIt() {
        JFileChooser fc = new JFileChooser(".");
        if (fc.showSaveDialog(null) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        String wPath = fc.getSelectedFile().toString();
        if (wPath.indexOf(".") == 0) {
            wPath = wPath.trim() + ".txt";
        }
        FileUtil.string2file_(wPath, txtLeft.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompare;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnWriteIt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtFile1;
    private javax.swing.JTextArea txtLeft;
    private javax.swing.JTextField txtLimit;
    // End of variables declaration//GEN-END:variables
	// ------------------------------------------------------------------------
    // main
    // ------------------------------------------------------------------------
    public static void main(String[] argv) {
        standAlone(new Pn_Head(), "Head　テキストファイルの先頭を見る");
    }
}
